### PR TITLE
#175743390 ft(languages): support multiple languages

### PR DESCRIPTION
**Pull request by SimonImanigirimpuhwe**
#### What does this PR do?

- Support multiple languages

#### Description of Task to be completed? 

- Install and set up `i18next`
- Install `i18next-http-backend` to fetch translations
- Add dropdown to change language
- Add languages `[English, French, Kinyarwanda, Swahili]` to be supported

#### How should this be manually tested?

- Clone the repo 

- In your home directory  cd this branch **`ft-support-multiple-languages-#175743390`**

- Then run **`npm install`** to install all dependencies

- Run **`npm start`** to start the server

- In your default browser navigate to **`http://localhost:3000`** 

> On the select choose any supported language and you should see text translated in the language of choice

#### Any background context you want to provide?

- N/A

#### What are the relevant Pivotal Tracker stories?

- [#175743390](https://www.pivotaltracker.com/n/projects/2476677/stories/175743390)

#### Screenshots (if appropriate)

- 
Screen Shot 2021-02-15 at 10 57 38

#### Questions:

- N/A

### CODE REVIEW

**Review by leny62 — CHANGES_REQUESTED** [review]
I am attaching images portraying some changes I would recommend regarding "Kinyarwanda language"
Screen Shot 2021-02-15 at 13 20 07

**Review by leny62 — APPROVED** [review]

**Comment by SimonImanigirimpuhwe** [comment]
@leny62 ,
Actually, I don't translate that manually...means nothing I can  do on that. That is the poor Google translation of `Kinyarwanda`, let's hope later `Google` will improve `Kinyarwanda` translations.

**Review by furebo — APPROVED** [review]
Amazing , Application can support 5 languages !

**Review by SamuelSabasNayo — APPROVED** [review]
Good work!

**Pull request merged**
