### PR TITLE
#176037917 ft(faq): Frequently Asked Questions

### PR DESCRIPTION
**Pull request by SamuelSabasNayo**
### What does this PR do?
- Implement FAQ page.

### Description of Task to be completed?
- Implement FAQ page for desktop view.
- Implement FAQ page for mobile view.

### How should this be manually tested?
- Clone the repository.
- In your home directory  move  into the cloned folder by **cd ft-faq-176037917**
- Then run **npm install** to install all dependencies.
- Run **npm start** to start the server.

### Any background context you want to provide?
- N/A

### What are the relevant Pivotal Tracker stories?
- [#176037917](https://www.pivotaltracker.com/n/projects/2476677)

### Screenshots (if appropriate)
- 
#### Desktop View
Screen Shot 2020-12-19 at 19 07 46

#### Mobile View
Screen Shot 2020-12-19 at 19 08 57

### Questions
- N/A

### CODE REVIEW

**Review by thepatrickniyo — APPROVED** [review]

**Comment by malaba6** [comment]
Good job on the implementation Samuel, please write tests for the component and make sure this page is responsive, then this PR will be ready.

**Review by thepatrickniyo — APPROVED** [review]

**Comment by SamuelSabasNayo** [comment]
@team, you can review my PR.

**Comment by SamuelSabasNayo** [comment]
Hello @PatrickNiyogitare28 @SimonImanigirimpuhwe @ConstantineMaliza @marcelniyi, please review my PR for merging. Thanks!

**Review by thepatrickniyo — APPROVED** [review]

**Review by marcelniyi — APPROVED** [review]

**Comment by SamuelSabasNayo** [comment]
@here, Please review my PR.

**Review by ConstantineMaliza — APPROVED** [review]
great work @SamuelSabasNayo

**Comment by SamuelSabasNayo** [comment]
Welcome my good friend @ConstantineMaliza!

**Review by thepatrickniyo — APPROVED** [review]

**Pull request merged**
