### PR TITLE
#175931425 ft: Added Header and Footer

### PR DESCRIPTION
**Pull request by SamuelSabasNayo**
### What does this PR do?
- Implement header and footer.

### Description of Task to be completed?
- Implement header and footer for desktop view.
- Implement header and footer for mobile view.
- Write tests for header and footer.

### How should this be manually tested?
- Clone the repository.
- In your home directory  move  into the cloned folder by **cd ft-header-footer-#175931425**
- Then run **npm install** to install all dependencies.
- Run **npm start** to start the server.

### Any background context you want to provide?
- N/A

### What are the relevant Pivotal Tracker stories?
- [#175931425](https://www.pivotaltracker.com/n/projects/2476677)

### Screenshots (if appropriate)
- **Desktop View**
Screen Shot 2020-12-05 at 20 06 33

- **Mobile View**
Screen Shot 2020-12-05 at 20 07 17

### Questions
- N/A

### CODE REVIEW

**Review by thepatrickniyo — CHANGES_REQUESTED** [review]
Good work @SamuelSabasNayo! Your Features are almost as they are expected to be. And I kindly request to reduce the `opacity` of the header shadow then we be good to go.

**Review by ConstantineMaliza — CHANGES_REQUESTED** [review]
@SamuelSabasNayo great work for the feedback you can design professional logo and replace the word BFND

**Review by SimonImanigirimpuhwe — COMMENTED** [review]
Consider taking care of conflicting file.

**Comment by SamuelSabasNayo** [comment]
@PatrickNiyogitare28 I will work on it.
@ConstantineMaliza Just to let you know that @marcelniyi accepted to work on a Logo.
Once he submit to me, I will include it in my codes.
@SimonImanigirimpuhwe I will take care of conflicts.

**Review by marcelniyi — APPROVED** [review]

**Review by thepatrickniyo — APPROVED** [review]

**Review by Monehin — COMMENTED** [review]
Good work 👍

**Review by Monehin — APPROVED** [review]

**Pull request merged**
