### PR TITLE
#176384986 ft(signup): integrate signup

### PR DESCRIPTION
**Pull request by SimonImanigirimpuhwe**
#### What does this PR do?

- Integrate backend (signup)

#### Description of Task to be completed? 

- Set signup context
- Add client validations
- Connect frontend to the backend

#### How should this be manually tested?

- Clone the repo 

- In your home directory  cd this branch **`ft-integrate-signup-#176384986`**

- Then run **`npm install`** to install all dependencies

- Run **`npm start`** to start the server

- In your default browser navigate to **`http://localhost:3000/signup`**

> When successfully reached the dashboard

#### Any background context you want to provide?

- To successfully send request to the backend you need to put backend url in `.env` file

#### What are the relevant Pivotal Tracker stories?

- [#176384986](https://www.pivotaltracker.com/n/projects/2476677/stories/176384986)

#### Screenshots (if appropriate)

- N/A

#### Questions:

- N/A

### CODE REVIEW

**Comment by SamuelSabasNayo** [comment]
@SimonImanigirimpuhwe, What credentials are we going to use?
Below is what I get when I use other credentials, even John Doe credentials do not work.

Screen Shot 2021-01-09 at 11 47 31

**Review by SamuelSabasNayo — COMMENTED** [review]
@SimonImanigirimpuhwe, What credentials are we going to use?
Below is what I get when I use other credentials, even John Doe credentials do not work.

Screen Shot 2021-01-09 at 11 47 31

**Review by ConstantineMaliza — CHANGES_REQUESTED** [review]
Great work @SimonImanigirimpuhwe  there is a small issue  when you are trying to signup
image

**Comment by SimonImanigirimpuhwe** [comment]
> Great work @SimonImanigirimpuhwe there is a small issue when you are trying to signup
> image

THis is not an issue but you are testing without putting the backend url in `.env`

**Comment by SimonImanigirimpuhwe** [comment]
> @SimonImanigirimpuhwe, What credentials are we going to use?
> Below is what I get when I use other credentials, even John Doe credentials do not work.
> 
> Screen Shot 2021-01-09 at 11 47 31

You have to put backend url in your `.env` otherwise it will not work

**Comment by SimonImanigirimpuhwe** [comment]
> @SimonImanigirimpuhwe, What credentials are we going to use?
> Below is what I get when I use other credentials, even John Doe credentials do not work.
> 
> Screen Shot 2021-01-09 at 11 47 31

@ConstantineMaliza  @SamuelSabasNayo  consider reading steps to test this PR

**Review by ConstantineMaliza — APPROVED** [review]

**Review by SamuelSabasNayo — APPROVED** [review]

**Pull request merged**
