### PR TITLE
#175743401 ft(signup): add user signup page

### PR DESCRIPTION
**Pull request by SimonImanigirimpuhwe**
#### What does this PR do?

- Implement user signup page

#### Description of Task to be completed? 

- Implement the signup form

- Implement mobile view of the page

- Write tests of the page

#### How should this be manually tested?

- Clone the repo 

- In your home directory  cd this branch **`ft-signup-page-#175743401`**

- Then run **`npm install`** to install all dependencies

- Run **`npm start`** to start the server

- Run **`npm test`** to run tests

- In your default browser navigate to **`http://localhost:3000/signup`**

> You should see a signup form 

#### Any background context you want to provide?

- N/A

#### What are the relevant Pivotal Tracker stories?

- [#175743401](https://www.pivotaltracker.com/n/projects/2476677/stories/175743401)

#### Screenshots (if appropriate)

Screen Shot 2020-12-02 at 10 19 56

#### Questions:

- N/A

### CODE REVIEW

**Comment by PatrickNiyogitare28** [comment]
Good work  @SimonImanigirimpuhwe! 
This are the few issues to consider.
- The social media login/signup button labels should be in the center if possible.
- Of couse the font-family should be popins

**Comment by PatrickNiyogitare28** [comment]
> Good work @SimonImanigirimpuhwe!
> This are the few issues to consider.
> 
> * The social media login/signup button labels should be in the center if possible.
> * Of couse the font-family should be popins

**Review by thepatrickniyo — CHANGES_REQUESTED** [review]
Good work  @SimonImanigirimpuhwe! 
This are the few issues to consider.
- The social media login/signup button labels should be in the center if possible.
- Of couse the font-family should be popins

**Comment by SimonImanigirimpuhwe** [comment]
> Good work @SimonImanigirimpuhwe!
> This are the few issues to consider.
> 
> * The social media login/signup button labels should be in the center if possible.
> * Of couse the font-family should be popins

@PatrickNiyogitare28  Confirm if I appropriately responded to the changes you requested

**Review by thepatrickniyo — APPROVED** [review]
cool @SimonImanigirimpuhwe, It's ok now. we are good to go.

**Comment by marcelniyi** [comment]
Everythings is nice but a few considerations:
- for the **styles** to be in a separate file
- using **components** instead of views @Monehin 

please let me know if the navbar you used is common to be used for all pages

**Comment by SimonImanigirimpuhwe** [comment]
> Everythings is nice but a few considerations:
> 
> * for the **styles** to be in a separate file
> * using **components** instead of views @Monehin
> 
> please let me know if the navbar you used is common to be used for all pages


> Everythings is nice but a few considerations:
> 
> * for the **styles** to be in a separate file
> * using **components** instead of views @Monehin

@marcelniyi Thanks for your comments. But if you have read the shared doc about the structure of project, we are having views where pages should be. 
For the styles I was actually avoiding more nested access object but for the separation of concerns I will refactor my codes.

> Note that for the header that is dummy one.

**Review by SamuelSabasNayo — APPROVED** [review]

**Review by marcelniyi — APPROVED** [review]

**Review by ConstantineMaliza — APPROVED** [review]

**Pull request merged**
