### PR TITLE
#176331258 ft(contact-us): Added contact us page

### PR DESCRIPTION
**Pull request by SamuelSabasNayo**
### What does this PR do?
- Implement the contact-us page.

### Description of Task to be completed?
- Implement the contact-us page for desktop view.
- Implement the contact-us page for mobile view.
- Write tests for the contact-us page.

### How should this be manually tested?
- Clone the repository.
- In your home directory  move  into the cloned folder by **cd ft-contact-us-#176331258**
- Then run **npm install** to install all dependencies.
- Run **npm start** to start the server.

### Any background context you want to provide?
- N/A

### What are the relevant Pivotal Tracker stories?
- [#176331258](https://www.pivotaltracker.com/n/projects/2476677)

### Screenshots (if appropriate)
- Desktop view
Screen Shot 2021-01-05 at 07 13 42

- Mobile view
Screen Shot 2021-01-05 at 07 13 50

### Questions
- N/A

### CODE REVIEW

**Review by thepatrickniyo — APPROVED** [review]

**Review by ConstantineMaliza — APPROVED** [review]

**Review by SimonImanigirimpuhwe — CHANGES_REQUESTED** [review]
Consider working on the mobile view of this feature... You can see that the form blocking styles on small size screens. You can also reduce the size of `contact us` tile just to avoid the title wrap.

Screen Shot 2021-01-06 at 09 38 12

**Comment by SamuelSabasNayo** [comment]
@SimonImanigirimpuhwe, your request is now responded.

**Review by SimonImanigirimpuhwe — APPROVED** [review]
Well done!

**Comment by malaba6** [comment]
image

**Comment by malaba6** [comment]
image

**Comment by malaba6** [comment]
I don't see tests written for this component

**Pull request merged**
